cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --nodes={resources.nodes}
    --ntasks={threads}
    --mem={resources.mem}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/smk-{rule}-{wildcards}-{jobid}.out
default-resources:
  - account="b1042"
  - partition=genomics
  - nodes=1
  - mem="5G"
  - time="02:00:00"
jobs: 10
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 5
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
