__default__:
  allocation: "p31588"
  partition: "short"
  cpus: "2"
  nodes: "1"
  time: 01:00:00
  mem: 5g"
  jobname: "{rule}_{wildcards}"
  output: "logs_slurm/{rule}_{wildcards}.out"
  error: "logs_slurm/{rule}_{wildcards}.error"
  email: "jacksumner2026@u.northwestern.edu"
  email_type: "FAIL"

index_human_genome:
  cpus: "{threads}"
  time: 04:00:00
  mem: "20g"

bwa_map:
  cpus: "{threads}"

fastp_pe:
  cpus: "{threads}"

metaphlan_setup:
  cpus: "{threads}"
  time: 04:00:00
  mem: "50g"

metaphlan:
  cpus: "{threads}"
  time: 04:00:00
  mem: "50g"

meahit_monoassemble:
  nodes: "1"
  cpus: "{threads}"
  time: 05:00:00
  partitgion: "normal"
  mem: "100g"

SS_map_reads_to_contigs:
  cpus: "{threads}"
  
SS_metabat2_depth:
  nodes: "1"
  cpus: "{threads}"
  time: 01:00:00
  partition: "short"
  mem: "60g"

SS_metabat2_bin:
  nodes: "1"
  cpus: "{threads}"
  time: 01:00:00
  partition: "short"
  mem: "60g"

SS_checkm_analysis:
  nodes: "1"
  cpus: "{threads}"
  time: 01:00:00
  partition: "short"
  mem: "36g"

